---
- name: "Import Homebrew play book"
  import_playbook: "play-books/homebrew.yml"

- name: Workstation setup
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: "Include vars"
      include_vars: "vars/main.yml"
      
    - name: "Include SSH tasks"
      import_tasks: "play-books/ssh.yml"

    - name: Install NPM Modules
      npm:
        name: "{{ item }}"
        global: yes
        state: present
      with_items:
        - bower
        - grunt
        - gulp
        - selenium-webdriver
        - chromedriver

  post_tasks:
    - name: "Update Local Configuration Files"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        backup: yes
        owner: "{{ username }}"
        group: "{{ group }}"
      with_items:
        - src: files/bash_profile.j2
          dest: "{{ homedir }}/.bash_profile"
        - src: files/.ansible.cfg
          dest: "{{ homedir }}/.ansible.cfg"

    - name: "Link {{ homedir }}/.bashrc to {{ homedir }}/.bash_profile"
      file:
        path:  "{{ homedir }}/.bashrc"
        state: link
        src: "{{ homedir }}/.bash_profile"

    - name: "Update Homebrew"
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
