---
- name: Homebrew Play Book
  hosts: localhost
  connection: local
  tasks:
    - name: "Include Vars"
      include_vars: "../vars/main.yml"
      
    - name: Install Brews
      homebrew:
        install_options: "{{ item.options }}"
        name: "{{ item.name }}"
        update_homebrew: yes
        upgrade_all: yes
      with_items: "{{ brew_taps }}"

    - name: "Link PHP version"
      homebrew:
        name: "php@{{ php_version }}"
        state: linked

    - name: Install Casks
      homebrew_cask:
        name: "{{ item.name }}"
        install_options: "{{ item.options }}"
      with_items: "{{ brew_casks }}"

    - name: "Install Atom packages"
      shell: "apm install {{ item }}"
      with_items: "{{ atom_packages }}"
      ignore_errors: yes

    - name: "Install Atom UI themes"
      shell: "apm install {{ item }}"
      with_items: "{{ atom_ui_themes }}"
      ignore_errors: yes

    - name: "Install Atom syntax themes"
      shell: "apm install {{ item }}"
      with_items: "{{ atom_syntax_themes }}"
      ignore_errors: yes
